---
- name: Install Nginx using K3s (AMD64)
  hosts: localhost
  become: yes
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      ignore_errors: yes

    - name: Create Nginx directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/nginx/conf
        - /opt/nginx/html
        - /opt/nginx/logs

    - name: Create Nginx deployment yaml
      copy:
        dest: /opt/nginx/nginx-deployment.yml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24@sha256:f2f5da93ac629d6afd25f0dd07e63c4dd944772c0f3c21e5356b67591f8a3a03
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - name: nginx-conf
                    mountPath: /etc/nginx/conf.d
                  - name: nginx-html
                    mountPath: /usr/share/nginx/html
                  - name: nginx-logs
                    mountPath: /var/log/nginx
                volumes:
                - name: nginx-conf
                  hostPath:
                    path: /opt/nginx/conf
                - name: nginx-html
                  hostPath:
                    path: /opt/nginx/html
                - name: nginx-logs
                  hostPath:
                    path: /opt/nginx/logs
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: default
          spec:
            type: NodePort
            ports:
            - name: http
              port: 80
              targetPort: 80
              nodePort: 30080
            selector:
              app: nginx

    - name: Create default nginx config
      copy:
        dest: /opt/nginx/conf/default.conf
        content: |
          server {
              listen       80;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  index.html;
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }
          }

    - name: Create test page
      copy:
        dest: /opt/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Nginx (AMD64)</title>
          </head>
          <body>
              <h1>Welcome to Nginx (AMD64)</h1>
              <p>If you see this page, the Nginx container is working on AMD64 architecture.</p>
          </body>
          </html>

    - name: Deploy Nginx to K3s
      command: kubectl apply -f /opt/nginx/nginx-deployment.yml

    - name: Wait for Nginx deployment
      command: kubectl rollout status deployment/nginx -n default
      register: rollout_status
      until: rollout_status.rc == 0
      retries: 30
      delay: 10

    - name: Show Nginx status
      command: kubectl get pods -l app=nginx -n default
      register: nginx_status

    - name: Show Nginx pod status
      debug:
        var: nginx_status.stdout_lines

    - name: Show Nginx access info
      debug:
        msg: 
          - "Nginx is running (AMD64)"
          - "Access URL: http://YOUR_SERVER_IP:30080"
          - "Configuration directory: /opt/nginx/conf"
          - "HTML directory: /opt/nginx/html"
          - "Logs directory: /opt/nginx/logs" 