---
- name: Uninstall Prometheus Stack from K3s (ARM64)
  hosts: localhost
  become: yes
  tasks:
    - name: Delete Prometheus Stack deployment
      command: kubectl delete -f /opt/prometheus/prometheus-deployment.yml
      ignore_errors: yes

    - name: Wait for pods to be removed
      command: kubectl get pods -n default -l 'app in (prometheus,alertmanager,grafana)'
      register: pod_status
      until: pod_status.rc != 0 or pod_status.stdout == ""
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Remove Prometheus directories
      file:
        path: /opt/prometheus
        state: absent

    - name: Show cleanup status
      debug:
        msg: "Prometheus Stack (ARM64) has been uninstalled and cleaned up" 