---
- name: Uninstall RabbitMQ Container
  hosts: localhost
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /tmp/kubectl
        mode: '0755'
      ignore_errors: yes

    - name: Delete RabbitMQ deployment and service
      command: /tmp/kubectl delete -f /tmp/rabbitmq/rabbitmq-deployment.yml
      ignore_errors: yes

    - name: Wait for RabbitMQ pods to be removed
      command: /tmp/kubectl get pods -n default | grep rabbitmq
      register: pod_check
      until: pod_check.rc != 0
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Remove RabbitMQ directories
      file:
        path: /tmp/rabbitmq
        state: absent

    - name: Show cleanup status
      debug:
        msg: "RabbitMQ has been uninstalled and cleaned up" 