---
- name: Uninstall Nginx Container with Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Stop and remove Nginx container
      docker_container:
        name: nginx
        state: absent

    - name: Remove Nginx image
      docker_image:
        name: nginx:1.24
        state: absent

    - name: Remove Nginx directories
      file:
        path: /opt/nginx
        state: absent

    - name: Show cleanup status
      debug:
        msg: "Nginx Docker container has been uninstalled and cleaned up" 