---
- name: Uninstall RabbitMQ Container
  hosts: localhost
  tasks:
    - name: Delete RabbitMQ deployment and service
      command: kubectl delete -f /home/ubuntu/rabbitmq/rabbitmq-deployment.yml
      ignore_errors: yes

    - name: Wait for RabbitMQ pods to be removed
      command: kubectl get pods -n default | grep rabbitmq
      register: pod_check
      until: pod_check.rc != 0
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Remove RabbitMQ directories
      file:
        path: /home/ubuntu/rabbitmq
        state: absent

    - name: Show cleanup status
      debug:
        msg: "RabbitMQ has been uninstalled and cleaned up" 