---
- name: Uninstall Nginx Container
  hosts: localhost
  become: yes
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      ignore_errors: yes

    - name: Delete Nginx deployment and service
      command: kubectl delete -f /opt/nginx/nginx-deployment.yml
      ignore_errors: yes

    - name: Wait for Nginx pods to be removed
      command: kubectl get pods -n default | grep nginx
      register: pod_check
      until: pod_check.rc != 0
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Remove Nginx directories
      file:
        path: /opt/nginx
        state: absent

    - name: Show cleanup status
      debug:
        msg: "Nginx has been uninstalled and cleaned up" 