---
- name: Uninstall RabbitMQ Container (ARM64)
  hosts: localhost
  become: yes
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/arm64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      failed_when: false

    - name: Delete RabbitMQ deployment and service
      command: kubectl delete -f /opt/rabbitmq/rabbitmq-deployment.yml
      failed_when: false

    - name: Wait for RabbitMQ pods to be removed
      command: kubectl get pods -n default | grep rabbitmq
      register: pod_check
      until: pod_check.rc != 0
      retries: 30
      delay: 10
      failed_when: false

    - name: Remove RabbitMQ directories
      file:
        path: /opt/rabbitmq
        state: absent

    - name: Show cleanup status
      debug:
        msg: "RabbitMQ has been uninstalled and cleaned up (ARM64)"
