---
- name: Install Nginx using K3s (AMD64)
  hosts: localhost
  become: yes
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      failed_when: false

    - name: Create Nginx directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/nginx/conf
        - /opt/nginx/html
        - /opt/nginx/logs

    - name: Create Nginx deployment yaml
      template:
        src: templates/nginx-deployment.yml.j2
        dest: /opt/nginx/nginx-deployment.yml
        mode: '0644'

    - name: Create default nginx config
      template:
        src: templates/default.conf.j2
        dest: /opt/nginx/conf/default.conf
        mode: '0644'

    - name: Create test page
      template:
        src: templates/index.html.j2
        dest: /opt/nginx/html/index.html
        mode: '0644'

    - name: Deploy Nginx to K3s
      command: kubectl apply -f /opt/nginx/nginx-deployment.yml

    - name: Wait for Nginx deployment
      command: kubectl rollout status deployment/nginx -n default
      register: rollout_status
      until: rollout_status.rc == 0
      retries: 30
      delay: 10

    - name: Show Nginx status
      command: kubectl get pods -l app=nginx -n default
      register: nginx_status

    - name: Show Nginx pod status
      debug:
        var: nginx_status.stdout_lines

    - name: Show Nginx access info
      debug:
        msg:
          - "Nginx is running (AMD64)"
          - "Access URL: http://YOUR_SERVER_IP:30080"
          - "Configuration directory: /opt/nginx/conf"
          - "HTML directory: /opt/nginx/html"
          - "Logs directory: /opt/nginx/logs"

    - name: Delete Nginx deployment and service
      command: kubectl delete -f /opt/nginx/nginx-deployment.yml
      failed_when: false
