---
- name: Install Nginx using K3s
  hosts: localhost
  become: yes
  tasks:
    - name: Create Nginx directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/nginx/conf
        - /opt/nginx/html
        - /opt/nginx/logs

    - name: Create default nginx config
      template:
        src: templates/default.conf.j2
        dest: /opt/nginx/conf/default.conf
        mode: '0644'

    - name: Create test page
      template:
        src: templates/index.html.j2
        dest: /opt/nginx/html/index.html
        mode: '0644'

    - name: Create Nginx deployment yaml
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginx:1.24
                    ports:
                      - containerPort: 80
                    volumeMounts:
                      - name: nginx-conf
                        mountPath: /etc/nginx/conf.d
                      - name: nginx-html
                        mountPath: /usr/share/nginx/html
                      - name: nginx-logs
                        mountPath: /var/log/nginx
                volumes:
                  - name: nginx-conf
                    hostPath:
                      path: /opt/nginx/conf
                  - name: nginx-html
                    hostPath:
                      path: /opt/nginx/html
                  - name: nginx-logs
                    hostPath:
                      path: /opt/nginx/logs

    - name: Create Nginx service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: default
          spec:
            type: NodePort
            ports:
              - name: http
                port: 80
                targetPort: 80
                nodePort: 30080
            selector:
              app: nginx

    - name: Wait for Nginx deployment
      kubernetes.core.k8s_info:
        kind: Deployment
        name: nginx
        namespace: default
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Available
          status: "True"

    - name: Show Nginx access info
      debug:
        msg:
          - "Nginx is running"
          - "Access URL: http://YOUR_SERVER_IP:30080"
          - "Configuration directory: /opt/nginx/conf"
          - "HTML directory: /opt/nginx/html"
          - "Logs directory: /opt/nginx/logs"
