---
- name: Uninstall Nginx from Kubernetes
  hosts: localhost
  become: yes
  tasks:
    - name: Delete Service
      k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: web

    - name: Delete Deployment
      k8s:
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: web

    - name: Delete ConfigMaps
      k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ item }}"
            namespace: web
      with_items:
        - nginx-config
        - nginx-html

    - name: Wait for resources to be removed
      k8s_info:
        kind: Pod
        namespace: web
        label_selectors:
          - app=nginx
      register: pod_status
      until: pod_status.resources | length == 0
      retries: 30
      delay: 10

    - name: Delete namespace
      k8s:
        name: web
        api_version: v1
        kind: Namespace
        state: absent

    - name: Remove Nginx directories
      file:
        path: /opt/nginx/k8s
        state: absent

    - name: Show cleanup status
      debug:
        msg: "Nginx has been uninstalled from Kubernetes"
